/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	interlaceprofilev1beta1 "github.com/argoproj-labs/argocd-interlace/pkg/apis/interlaceprofile/v1beta1"
	versioned "github.com/argoproj-labs/argocd-interlace/pkg/client/interlaceprofile/clientset/versioned"
	internalinterfaces "github.com/argoproj-labs/argocd-interlace/pkg/client/interlaceprofile/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/argoproj-labs/argocd-interlace/pkg/client/interlaceprofile/listers/interlaceprofile/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InterlaceProfileInformer provides access to a shared informer and lister for
// InterlaceProfiles.
type InterlaceProfileInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.InterlaceProfileLister
}

type interlaceProfileInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInterlaceProfileInformer constructs a new informer for InterlaceProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInterlaceProfileInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInterlaceProfileInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInterlaceProfileInformer constructs a new informer for InterlaceProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInterlaceProfileInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InterlaceV1beta1().InterlaceProfiles(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InterlaceV1beta1().InterlaceProfiles(namespace).Watch(context.TODO(), options)
			},
		},
		&interlaceprofilev1beta1.InterlaceProfile{},
		resyncPeriod,
		indexers,
	)
}

func (f *interlaceProfileInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInterlaceProfileInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *interlaceProfileInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&interlaceprofilev1beta1.InterlaceProfile{}, f.defaultInformer)
}

func (f *interlaceProfileInformer) Lister() v1beta1.InterlaceProfileLister {
	return v1beta1.NewInterlaceProfileLister(f.Informer().GetIndexer())
}
