/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	applicationprovenancev1beta1 "github.com/argoproj-labs/argocd-interlace/pkg/apis/applicationprovenance/v1beta1"
	versioned "github.com/argoproj-labs/argocd-interlace/pkg/client/applicationprovenance/clientset/versioned"
	internalinterfaces "github.com/argoproj-labs/argocd-interlace/pkg/client/applicationprovenance/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/argoproj-labs/argocd-interlace/pkg/client/applicationprovenance/listers/applicationprovenance/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ApplicationProvenanceInformer provides access to a shared informer and lister for
// ApplicationProvenances.
type ApplicationProvenanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ApplicationProvenanceLister
}

type applicationProvenanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewApplicationProvenanceInformer constructs a new informer for ApplicationProvenance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewApplicationProvenanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredApplicationProvenanceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredApplicationProvenanceInformer constructs a new informer for ApplicationProvenance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredApplicationProvenanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InterlaceV1beta1().ApplicationProvenances(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InterlaceV1beta1().ApplicationProvenances(namespace).Watch(context.TODO(), options)
			},
		},
		&applicationprovenancev1beta1.ApplicationProvenance{},
		resyncPeriod,
		indexers,
	)
}

func (f *applicationProvenanceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredApplicationProvenanceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *applicationProvenanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&applicationprovenancev1beta1.ApplicationProvenance{}, f.defaultInformer)
}

func (f *applicationProvenanceInformer) Lister() v1beta1.ApplicationProvenanceLister {
	return v1beta1.NewApplicationProvenanceLister(f.Informer().GetIndexer())
}
